<?php


/**
 * [BEGIN_COT_EXT]
 * Code=sociolizer
 * Name=sociolizer
 * Description=Adds social likes to pages
 * Version=1.0.1
 * Date=2012-03-10
 * Author=esclkm
 * Auth_guests=R
 * Lock_guests=12345A
 * Auth_members=RW
 * [END_COT_EXT]
 * 
 * [BEGIN_COT_EXT_CONFIG]
 * fb=01:radio::1:facebook
 * ya=02:radio::1:ya.ru
 * mailru=03:radio::1:Mail.ru + Одноклассники
 * vk=04:string::API_ID:В контакте (введите ID)
 * twitter=05:string::esclkm:twitter от
 * google=06:radio::1:google +1
 * odno=06:radio::1:Одноклассники 
 * fbapi=07:string::API_ID:facebook (введите ID)
 * yashare=08:radio::1:яндекс шаре
 * [END_COT_EXT_CONFIG]
 * 
 *  */

/**
 * plugin sociolizer for Cotonti Siena
 * 2847608
 * @package sociolizer
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL');

?>
