<?php

/**
 * plugin sociolizer for Cotonti Siena
 * 
 * @package sociolizer
 * @version 1.0.0
 * @author esclkm
 * @copyright 
 * @license BSD
 *  */
// Generated by Cotonti developer tool (littledev.ru)
defined('COT_CODE') or die('Wrong URL.');

define('ТЕКСТ', 'ТЕКСТ страницы');
define('ЗАГОЛОВОК', 'ТЕКСТ страницы');
define('URL', 'ТЕКСТ страницы');
define('ESCAPEDURL', 'ТЕКСТ страницы');

global $sociolizer;
$sociolizer = array();
if ($cfg['plugin']['sociolizer']['vk'])
{
	$sociolizer['vk']['b'] = '<div id="vk_like"></div>';
	$sociolizer['vk']['h'] = '
	(function(w, d) {var u = [\'//userapi.com/js/api/openapi.js?48\'], i = u.length, n = \'script\', f = d.createDocumentFragment(), e = d.createElement(n), t;
  while (i--) { t = e.cloneNode(false); t.async = t.src = u[i]; f.appendChild(t);}
  (t = d.getElementsByTagName(n)[0]).parentNode.insertBefore(f, t);}(this, document));
	window.vkAsyncInit = function() {
	VK.init({ apiId: ' . $cfg['plugin']['sociolizer']['vk'] . ', onlyWidgets: true});
	VK.Widgets.Like("vk_like", {type: "button", verb: 1, text: "{$text}", pageUrl: "{$url}", pageTitle: "{$title}"});};';
}

if ($cfg['plugin']['sociolizer']['fb'])
{
	$sociolizer['fb']['b'] = '<div class="fb-like" data-href="{$escaped}" data-layout="button_count" data-send="false" data-width="200" data-show-faces="true" data-action="recommend"></div>';
	$sociolizer['fb']['h'] = '(function(d, s, id) {  var js, fjs = d.getElementsByTagName(s)[0];  if (d.getElementById(id)) return;  js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1&appId='.$cfg['plugin']['sociolizer']['fbapi'].'";  fjs.parentNode.insertBefore(js, fjs);}(document, \'script\', \'facebook-jssdk\'));';
}

if($cfg['plugin']['sociolizer']['ya'])
{
	$sociolizer['ya']['b'] = '<a counter="yes" type="button" size="large" share_url="{$url}" share_title="{$title}" name="ya-share"> </a>';
	
	$sociolizer['ya']['h'] = 'if (window.Ya && window.Ya.Share) {Ya.Share.update();} else {(function(){if(!window.Ya) { window.Ya = {} };Ya.STATIC_BASE = \'http:\/\/yandex.st\/wow\/2.3.21\/static\';Ya.START_BASE = \'http:\/\/my.ya.ru\/\';var shareScript = document.createElement("script");shareScript.type = "text/javascript";shareScript.async = "true";shareScript.charset = "utf-8";shareScript.src = Ya.STATIC_BASE + "/js/api/Share.js";(document.getElementsByTagName("head")[0] || document.body).appendChild(shareScript);})();}';
}

if($cfg['plugin']['sociolizer']['mailru'])
{
	$sociolizer['mail']['b'] = '<a target="_blank" class="mrc__plugin_uber_like_button" href="http://connect.mail.ru/share?share_url={$escaped}" data-mrc-config="{\'type\' : \'button\', \'caption-mm\' : \'2\', \'caption-ok\' : \'2\', \'counter\' : \'true\', \'width\' : \'100%\', \'nt\' : \'1\'}">Нравится</a><script src="http://cdn.connect.mail.ru/js/loader.js" type="text/javascript"></script>';
}

if($cfg['plugin']['sociolizer']['twitter'])
{
	$sociolizer['twitter']['b'] = '<a href="https://twitter.com/share" class="twitter-share-button" data-url="{$url}" data-text="{$title}" data-hashtags="'.$cfg['plugin']['sociolizer']['twitter'].'" data-lang="ru">Твитнуть</a>';
	$sociolizer['twitter']['h'] = '!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");';
}

if($cfg['plugin']['sociolizer']['google'])
{
	$sociolizer['google']['b'] = '<div class="g-plusone" data-size="medium" data-href="{$url}"></div>';
	$sociolizer['google']['h'] = 'window.___gcfg = {lang: \'ru\'}; (function() { var po = document.createElement(\'script\'); po.type = \'text/javascript\'; po.async = true; po.src = \'https://apis.google.com/js/plusone.js\'; var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(po, s); })()';
}

if($cfg['plugin']['sociolizer']['odno'])
{
	$sociolizer['odno']['b'] = '<a class="odkl-klass-stat" href="{$url}"><span>0</span></a>';
	$sociolizer['odno']['h'] = 'head.js("http://stg.odnoklassniki.ru/share/odkl_share.js", function() {
			$(window).load(function(){
			ODKL.init();
		$(\'.odkl-klass-stat\').click(function(){ODKL.Share(this);return false;});
		});
	});';
}
if($cfg['plugin']['sociolizer']['yashare'])
{
	$sociolizer['yashare']['b'] = '<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,gplus,lj,moikrug"></div>';
	$sociolizer['yashare']['h'] = 'head.js("//yandex.st/share/share.js");';
}
?>